### ISSUE TITLE
a typo in the https://docs.advanced-peripherals.de/peripherals/me_bridge/#listcells part of the wiki

### ISSUE THREAD

**Issue by joeyjo33** [SirEndii/Advanced-Peripherals-Documentation#75]
### Describe

there is a typo in the documentation i have found wile reading the https://docs.advanced-peripherals.de/peripherals/me_bridge/#listcells documentation, see added screenshot for more info
![Knipsel](https://github.com/SirEndii/Advanced-Peripherals-Documentation/assets/91799218/b1ae021b-27b6-4180-87d9-225e47885c7c)

### Steps to reproduce

check https://docs.advanced-peripherals.de/peripherals/me_bridge/#listcells to see the problem

### Direct URL

https://docs.advanced-peripherals.de/peripherals/me_bridge/#listcells

**Comment by soer7022** [comment]
You can submit a pull request with the fixes, check this guide: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github if you're new to the whole github thing 😄

**Comment by joeyjo33** [comment]
its a typo on the website. as far as i can see in the github repo there is
nothing related to that

Op do 2 nov. 2023 22:44 schreef Søren Skov Eriksen ***@***.***

**Comment by soer7022** [comment]
The website is generated from the 'docs' folder

**Comment by joeyjo33** [comment]
> The website is generated from the 'docs' folder

elaborate on what generates the website, all i see is a RELEASE.md

**Comment by soer7022** [comment]
Are you looking at the main branch?

**Comment by joeyjo33** [comment]
i by accident went and git clone the repo. i now forked the branche and
changed the thing i neede to change:
https://github.com/joeyjo33/Advanced-Peripherals-Documentation

Op vr 3 nov. 2023 16:34 schreef Søren Skov Eriksen ***@***.***

**Comment by joeyjo33** [comment]
the pull request has been created
